#!/usr/bin/env bash
# Run on the Command Central droplet (/opt/agent-tim) after: tailscale up
# Adds Postgres (crm-db) on the node's Tailscale IPv4 :5432 in addition to 127.0.0.1:5432.
# Idempotent: if the generated overlay is unchanged, skips `docker compose up` so crm-db is
# not recreated on every deploy (avoids "Connection terminated unexpectedly" / ECONNRESET for dev clients).
#
#   cd /opt/agent-tim && bash tools/expose-crm-db-tailscale.sh
#
set -euo pipefail
COMPOSE_DIR="${COMPOSE_DIR:-/opt/agent-tim}"
cd "$COMPOSE_DIR"

if [[ ! -f web/.env.local ]]; then
  echo "ERROR: web/.env.local missing (needed for docker compose --env-file)."
  exit 1
fi

if ! tailscale status >/dev/null 2>&1; then
  echo "Tailscale is not logged in on this server. Run: tailscale up"
  exit 1
fi

TS_IP=$(tailscale ip -4 2>/dev/null | head -1)
if [[ -z "$TS_IP" ]]; then
  echo "Could not read Tailscale IPv4 (tailscale ip -4)."
  exit 1
fi

OVER=docker-compose.crm-db-tailscale.generated.yml
TMP="${OVER}.tmp.$$"
cat >"$TMP" <<EOF
# Generated by expose-crm-db-tailscale.sh — do not edit by hand
services:
  crm-db:
    ports:
      - "${TS_IP}:5432:5432"
EOF

if [[ -f "$OVER" ]] && cmp -s "$TMP" "$OVER"; then
  rm -f "$TMP"
  echo "OK: Tailscale CRM overlay unchanged (${TS_IP}:5432) — left crm-db running."
  echo "Laptop .env.local (native Node): CRM_DB_HOST=${TS_IP} CRM_DB_PORT=5432"
  exit 0
fi

mv -f "$TMP" "$OVER"
docker compose --env-file web/.env.local -f docker-compose.yml -f "$OVER" up -d crm-db
echo "OK: CRM Postgres also on Tailscale ${TS_IP}:5432 (127.0.0.1:5432 unchanged)."
echo "Laptop .env.local (native Node): CRM_DB_HOST=${TS_IP} CRM_DB_PORT=5432"
echo "Tunnel over tailnet: CRM_SSH_HOST=${TS_IP} in crm-db-tunnel.ps1 / .sh"
